server:
  port: 7901
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
        name: microservice-provider-user #建议大家全部使用小写
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://user:password123@localhost:8761/eureka
      #应该多注册几个节点，否则注册的节点万一当掉了，咋弄呢
      #defaultZone: http://peer1:8761/eureka,http://peer1:8762/eureka,http://peer1:8763/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    #自定义metadata-map
    metadata-map:
      zone: ABC    #eureka可以理解的元数据
      wangrui: BBC #不会影响客户端行为
    lease-renewal-interval-in-seconds: 5
    #appname:  microservice-provider-user #填坑，一般不会去使用的
    #hostname: user #指定该服务的主机名是什么，可以通过http://user:7901/访问偶，此时需要将instance-id，prefer-ip-address注释哦
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG

